version: '3'

services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3003:3000
    volumes:
      - .:/home/node/app
  
  db:
    image: postgres
    restart: always
    tty: true
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgt
    volumes:
      - ./.docker/db/postgres/data:/var/lib/postgresql/data_tmpfs:rw,tmpfs